name: Test Workflow

on:
  schedule:
    - cron: '* * * * *'  # This sets the job to run every minute

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "Running the test workflow at $(date)" >> test.log
          # You can replace the above line with your actual commands or scripts